src/main/java/com/google/swarm/tokenization/common/Util.java
src/test/java/com/google/swarm/tokenization/common/UtilTest.java

Add unittest for Utils.java

---

src/main/java/com/google/swarm/tokenization/common/CSVContentProcessorDoFn.java
src/test/java/com/google/swarm/tokenization/common/CSVStreamingPipelineTest.java
src/test/java/com/google/swarm/tokenization/common/DLPTokenizationDoFnTest.java

I am using a different branch for these specific tests to avoid merging too many things at once but am basing this off of your branch

Dlp unittests for CSVDoFn

---

README.md
terraform_setup/bq_schema.json
terraform_setup/main.tf

Masud, no rush on this but wanted to share my Terraform script for setting up resources for the demo.

Create Terraform File for quick prereq setup for demo

---

gradle/wrapper/gradle-wrapper.properties
gradlew
gradlew.bat
src/main/java/com/google/swarm/tokenization/DLPTextToBigQueryStreamingV2.java
src/main/java/com/google/swarm/tokenization/common/BatchRequestForDLP.java
src/main/java/com/google/swarm/tokenization/common/DLPTransform.java
src/main/java/com/google/swarm/tokenization/common/InspectData.java
src/main/java/com/google/swarm/tokenization/common/Util.java

- Upgraded gradle to 5.1 & removed redundant imports
- added bagged rows counter
- enhanced the findings schema with additional metadata to track Job Name for inspection jobs
- added support to track truncated findings
- additional counters to track DLP api calls count and rows inspected and bad rows (Header not matching the columns count) for inspection
- setup configuration to include quote in inspection results
- enhanced the findings schema to capture the field_id for identified info types

Proposed Changes to refine the inspection pipeline

---

src/main/java/com/google/swarm/tokenization/DLPTextToBigQueryStreamingV2.java

Making pub sub publish optional for reid

making pubsub publish optional

---

src/main/java/com/google/swarm/tokenization/DLPTextToBigQueryStreamingV2PipelineOptions.java
src/main/java/com/google/swarm/tokenization/avro/AvroReaderSplittableDoFn.java
src/main/java/com/google/swarm/tokenization/beam/DLPDeidentifyText.java
src/main/java/com/google/swarm/tokenization/beam/DLPInspectText.java
src/main/java/com/google/swarm/tokenization/beam/DLPReidentifyText.java
src/main/java/com/google/swarm/tokenization/beam/ShardRows.java
src/main/java/com/google/swarm/tokenization/common/BigQueryDynamicWriteTransform.java
src/main/java/com/google/swarm/tokenization/common/SanitizeFileNameDoFn.java
src/main/java/com/google/swarm/tokenization/json/JsonReaderSplitDoFn.java

Testing done:
Ran gradle build
Verified the diff manually

chore: Listing. Ran gradle spotlessApply

---

.gitignore
README.md
deploy-data-tokeninzation-solution-v2.sh
dlp_tokenizing_runner_permissions.yaml

inital draft - includes restructuring and updated links

---

README.md

Additional updates on readme revamp task.

Additional changes to README.md

---

.github/workflows/deid-run.yml

Added GitHub action to trigger a de-identification pipeline and run the verification tests defined in the yml script.
This was tested on a forked repository.

Added deid pipeline workflow

---

.github/workflows/deid-run.yml

Updated GitHub action config for newly created project "dlp-dataflow-deid-ci". Tested the workflow on a test self-hosted runner setup done on the testing VM instance "dlp-dataflow-deid-vm-test" under the same project.

Ci workflow testing

---

README.md

Updating README with final review changes provided by cathsantos@.

Updates in README as recommended by cathsantos@

---

README.md
src/main/java/com/google/swarm/tokenization/common/Util.java

<h4> Summary (Short summary of what is being done) : </h4>  Minor fixes
<br>
- Added tsv extension in ALLOWED_FILE_EXTENSIONS
- Minor change in sample command in readme 
Tested the pipeline for a tsv file

Minor bug fixes

---

build.gradle
src/main/java/com/google/swarm/tokenization/DLPTextToBigQueryStreamingV2.java
src/main/java/com/google/swarm/tokenization/DLPTextToBigQueryStreamingV2PipelineOptions.java
src/main/java/com/google/swarm/tokenization/common/ExtractColumnNamesTransform.java
src/main/java/com/google/swarm/tokenization/common/Util.java
src/main/java/com/google/swarm/tokenization/orc/ORCColumnNameDoFn.java
src/main/java/com/google/swarm/tokenization/orc/ORCReaderSplittableDoFn.java

Creating this branch to collaborate with other team members. These are not final changes.
<br>
<br>
<br>
<br>

Orc support

---

README.md

<h4> Summary (Short summary of what is being done) : </h4> Added description about DLPParent in Readme
<br>
Added details about the parameter  --DLPParent  used to specify the resource location for DLP templates
Tested DEID of csv file using regional templates by passing the location in DLPParent param.

Added description about DLPParent in Readme

---

README.md
create-dlp-template.sh

Added steps to run the pipeline when user does not have access to Google cloud shell.
<br>
Modified the script to create DLP template and added instruction in README for the same.
<br>
<br>
<br>
Tested on GCE VM and local environment.

Add steps to Run this pipeline outside Google Cloud shell

---

.github/workflows/dlp-pipelines.yml

<h4> Summary (Short summary of what is being done) : </h4> CI Changes for GCS as sink
<br>
<br>Added workflow to test GCS as sink and verify the output files and number of rows in output files
Tested using workflow

Added CI changes for GCS as sink

---

.github/workflows/dlp-pipelines.yml
src/main/java/com/google/swarm/tokenization/DLPTextToBigQueryStreamingV2.java
src/main/java/com/google/swarm/tokenization/DLPTextToBigQueryStreamingV2PipelineOptions.java
src/main/java/com/google/swarm/tokenization/orc/ORCReaderDoFn.java
src/main/java/com/google/swarm/tokenization/orc/ORCWriterDoFn.java
src/test/java/com/google/swarm/tokenization/orc/ExtractFileSchemaTransformTest.java
src/test/java/com/google/swarm/tokenization/orc/ORCColumnNameDoFnTest.java
src/test/java/com/google/swarm/tokenization/orc/ORCReaderDoFnTest.java

Bug fix, automated tests and unit tests for ORC
<br>
1. Fixing the NullPointer issue with ORC file processing. 
<br>
2. Added CI verification tests and unit testing for ORC inspection and de-identification.
<br>
1. b/307245825
<br>
2. b/301563517
<br>
<br>
1. Used sample data provided by GSD team to verify the pipeline works as expected for fields with null values.
<br>
2. Please check GitHub PR checks.

Added automated test for ORC inspection

---

src/main/java/com/google/swarm/tokenization/InspectClassify.java
src/main/java/com/google/swarm/tokenization/classification/NewExtractColumnNamesTransform.java

Minor changes

---

README.md

Updating the limitaions on using complex file formats
<br>
Based on the recent debugging and research done on AVRO/Parquet/JSONL pipelines, there are some limitations in the existing implementation. This pull request updates the README guide to make users aware of those limitations. 
<br>
b/310711896
<br>
<br>
Not required.

Updating the limitaions on using complex file formats

---

src/main/java/com/google/swarm/tokenization/DLPTextToBigQueryStreamingV2.java
src/main/java/com/google/swarm/tokenization/orc/ExtractFileSchemaTransform.java
src/main/java/com/google/swarm/tokenization/parquet/ParquetWriterDoFn.java

added Parquet writer for GCS

---

src/main/java/com/google/swarm/tokenization/DLPTextToBigQueryStreamingV2.java
src/main/java/com/google/swarm/tokenization/avro/AvroColumnNamesDoFn.java
src/main/java/com/google/swarm/tokenization/orc/ExtractFileSchemaTransform.java
src/main/java/com/google/swarm/tokenization/parquet/GenericRecordFlattener.java
src/main/java/com/google/swarm/tokenization/parquet/ParquetWriterDoFn.java

Completed ParquetWriterDoFn and tested, need to write ParquetSink

---

.github/workflows/performance-testing-main.yml

test workflow dispatch
